version: '3'

networks:
  backend: {}

services:
  #---------------------------------------
  mongo:
    # database (only for develop)
    extends:
      file: docker-compose.e2e.yml
      service: mongo
    ports:
      # export for debug
      - 27017:27017
  #---------------------------------------
  postgres:
    # database (only for develop)
    extends:
      file: docker-compose.e2e.yml
      service: postgres
    ports:
      # export for debug
      - 5432:5432
