version: '3'

networks:
  backend: {}
  dapr: {}

services:
  #---------------------------------------
  verdaccio:
    image: verdaccio/verdaccio:nightly-master
    #
    ports:
      - '4873:4873'
    volumes:
      - './cnf/verdaccio:/verdaccio/storage'
      - './cnf/verdaccio:/verdaccio/conf'
  #---------------------------------------
  zipkin:
    #
    extends:
      file: docker-compose.e2e.yml
      service: zipkin
    ports:
      # export for dev
      - 9411:9411
  #---------------------------------------
  redis:
    #
    extends:
      file: docker-compose.e2e.yml
      service: redis
  #---------------------------------------
  mongo:
    #
    extends:
      file: docker-compose.e2e.yml
      service: mongo
    ports:
      # export for dev
      - 27017:27017
  #---------------------------------------
  postgres:
    #
    extends:
      file: docker-compose.e2e.yml
      service: postgres
    ports:
      # export for dev
      - 5432:5432
