version: '3.9'

networks:
  backend: {}
  dapr: {}
  dev: {}

services:
  #---------------------------------------
  verdaccio:
    image: verdaccio/verdaccio:5.24.1
    #
    networks:
      - dev
    volumes:
      - ./cnf/verdaccio:/verdaccio/storage
      - ./cnf/verdaccio:/verdaccio/conf:ro
  #---------------------------------------
  zipkin:
    #
    extends:
      file: docker-compose.e2e.yml
      service: zipkin
    ports:
      # export for dev
      - 9411:9411
  #---------------------------------------
  redis:
    #
    extends:
      file: docker-compose.e2e.yml
      service: redis
  #---------------------------------------
  mongo:
    #
    extends:
      file: docker-compose.e2e.yml
      service: mongo
    ports:
      # export for dev
      - 27017:27017
  #---------------------------------------
  postgres:
    #
    extends:
      file: docker-compose.e2e.yml
      service: postgres
    ports:
      # export for dev
      - 5432:5432
  #---------------------------------------
  postgrest:
    # https://postgrest.org/en/stable/
    image: postgrest/postgrest:latest
    #
    networks:
      - backend
      - dev
    depends_on:
      - postgres
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      PGRST_DB_URI: postgres://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@postgres:5432/${POSTGRESQL_DATABASE}
      # The name of which database schema to expose to REST clients
      PGRST_DB_SCHEMA: public
      # The database role to use when no client authentication is provided
      PGRST_DB_ANON_ROLE: ${POSTGRESQL_USERNAME}
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      #- PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
      # support image binary via Http Header: Accept
      PGRST_RAW_MEDIA_TYPES: image/jpeg, image/png
  #---------------------------------------
  caddy:
    # to install modules (godaddy, ...etc)
    build: ./cnf/caddy
    #
    ports:
      #- 80:8080
      #- 443:8443
      #- 443:8443/udp
      # verdaccio
      - 8873:8873
      # postgrest
      - 8432:8432
    depends_on:
      - verdaccio
      - postgrest
    networks:
      - dev
    volumes:
      - ./cnf:/data
      - ./cnf:/config
      - ./cnf/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      # https://developer.godaddy.com/keys
      GODADDY_TOKEN: ${GODADDYAPI_KEY}:${GODADDYAPI_SECRET}
  #---------------------------------------
  redis-stack:
    #
    image: redis/redis-stack-server:6.2.6-v7
    profiles: [ fixme ]
  #---------------------------------------
  autogpt:
    #
    image: significantgravitas/auto-gpt:v0.3.0
    profiles: [ fixme ]
    #
    depends_on:
      - redis-stack
    environment:
      #ALLOWLISTED_PLUGINS:
      MEMORY_BACKEND: redis
      REDIS_HOST: redis-stack
    volumes:
      #- ./.autogpt:/app/auto_gpt_workspace
      #- ./.autogpt:/app/data
      - ./.autogpt:/app/logs
  #---------------------------------------
  email:
    # https://hub.docker.com/r/postalsys/emailengine
    image: postalsys/emailengine:v2.32.14
    #
    networks:
      # redis is in dapr network
      - dapr
      - dev
    ports:
      # API and web interface
      - 3000:3000
      # SMTP for message submission
      - 2525:2525
    depends_on:
      - redis
    environment:
      # Encryption secret
      EENGINE_SECRET: secret
      # Database connection URL
      EENGINE_REDIS: redis://:${REDIS_PASSWORD}@redis:6379/8
      # Configuration to EmailEngine can be passed via environment variables
      # For full list see https://github.com/postalsys/emailengine#config-mapping

      # Settings to write to v1/settings on startup (https://api.emailengine.app/#operation/postV1Settings)
      # The following value is a YAML block scalar string, so make it sure it is properly indented
      # This configuration enables SMTP server for local submission
      EENGINE_SETTINGS: >
        {
            "smtpServerEnabled": true,
            "smtpServerPort": 2525,
            "smtpServerHost": "0.0.0.0",
            "smtpServerAuthEnabled": true,
            "smtpServerPassword": "passw0rd"
        }
