import '@io/lib/event'
export default Object.assign(Error, <ErrorConstructor>{
    Code(e) {
        return Object.assign(Error(e.message), e);
    }
});
declare global {
    interface ErrorConstructor {
        Code(e: Error): Error
    }
    interface Error {
        /**
        source of error
        */
        readonly cloudevent?: CloudEvent<string>
        /**
        how long to be wait if retryable, in milliseconds
        */
        readonly retrydelay?: number
        /**
        more description about this error, may contain technical details
        */
        readonly reason?: unknown
        /**
        */
        readonly params?: object
        /**
        */
        readonly errno?: number | string
        /**
        */
        readonly code?: number | string
        /**
        indicate the direction of the user
        */
        readonly help?: string
    }
    interface rfc7807 {
        /**
        a URI reference [RFC3986] that identifies the problem type.
        */
        readonly type?: string
        /**
        a short, human-readable summary of the problem type.
        */
        readonly title?: string
        /**
        the HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        */
        readonly status?: number
        /**
        a human-readable explanation specific to this occurrence of the problem.
        */
        readonly detail?: string
        /**
        a URI reference that identifies the specific occurrence of the problem.
        */
        readonly instance?: string
        /**
        extend the problem details object with additional members.
        */
        readonly [extensions: string]: unknown
    }
}