@startuml sequence
skinparam responseMessageBelowArrow true
autoactivate on
hide footbox
participant Agent as edge
actor PM as pm
actor BrandOwner as role
box Core
participant Backend as backend
participant LicenseService as service.lic
database Database as db
queue Broker as mb
end box
box Support
participant LicenseServer as lic.srv
end box
==create brand==
autonumber
role -> backend : 建立租戶
backend -> service.lic : 建立預設計費方案(Builder)
service.lic -> db : 保存設定
return Ok
return Ok
backend -> service.lic : 套用預設License
service.lic -> lic.srv : 查詢License內容
return 點數
service.lic -> lic.srv : 啟用License
return Ok
service.lic -> db : 保存License到租戶底下
return Ok
service.lic -> mb : 事件<BillingCreated>
return
return 套用成功
|||
return 租戶建立成功
==apply license==
autonumber
role -> backend : 輸入License Key
backend -> service.lic : 查詢內容
service.lic -> lic.srv : 查詢
return 點數
return
return
|||
role -> backend : 套用License
backend -> service.lic : 套用
service.lic -> lic.srv : 查詢License內容
return 點數
service.lic -> lic.srv : 啟用License
return Ok
service.lic -> service.lic : 增加餘額
alt 餘額不足 >>> 餘額正常
service.lic -> mb : 事件<BalanceRestored>
return
end
return
service.lic -> db : 保存餘額到租戶底下
return Ok
service.lic -> db : 保存License到租戶底下
return Ok
service.lic -> mb : 事件<LicensesApplied>
return
return Ok
return 套用成功
==calculator==
autonumber
role -> backend : 試算
backend -> service.lic
service.lic -> service.lic : 根據給定的條件試算
return
return 試算結果
return 試算結果
==change mode(待討論)==
autonumber
role -> backend : 切換mode
backend -> service.lic : 設定mode
alt 如果設定改變
service.lic -> db : 保存設定到租戶底下
return
service.lic -> service.lic : 重算 餘額
return
service.lic -> service.lic : 重算 剩餘天數
return
service.lic -> db : 保存狀態到租戶底下
return Ok
service.lic -> mb : 事件<BillingChanged>
return
end
return Ok
return 切換成功
==query cost==
autonumber
role -> backend : 查詢點數使用狀況
backend -> service.lic : 查詢點數使用狀況
service.lic -> db : 查詢
return
return
return 租戶cost狀況
==register devices(待討論)==
autonumber
edge -> backend : 註冊設備
backend -> service.lic : 註冊設備
service.lic -> service.lic : 每日扣點數 += N
return
service.lic -> service.lic : 重算 剩餘天數
return
service.lic -> db : 保存狀態到租戶底下
return Ok
service.lic -> mb : 事件<DevicesRegistered>
return
return
return 註冊成功
==disable devices(待討論)==
autonumber
==enable devices(待討論)==
autonumber
==remove devices(待討論)==
autonumber
role -> backend : 移除設備
backend -> service.lic : 移除設備
service.lic -> service.lic : 每日扣點數 -= N
return
service.lic -> service.lic : 重算 剩餘天數
return
service.lic -> db : 保存狀態到租戶底下
return Ok
service.lic -> mb : 事件<DevicesRemoved>
return
return
return 移除成功
==regular billing==
autonumber
?-> service.lic : 定期計費開始
loop 所有租戶
alt 租戶尚未停用
service.lic -> service.lic : 重算 餘額
return
service.lic -> service.lic : 重算 剩餘天數
return
service.lic -> db : 保存狀態到租戶底下
return Ok
alt 剩餘天數低於 剩餘天數門檻值
service.lic -> mb : 事件<BalanceIsLow>
return
end
alt 餘額低於 已用完門檻值
service.lic -> mb : 事件<OutOfBalance>
return
end
end
end
?<-- service.lic : 定期計費結束
==notification settings==
autonumber
pm -> backend : 調整 剩餘天數門檻值
backend -> service.lic
service.lic -> db : 保存設定到租戶底下
return Ok
return
return 成功
|||
pm -> backend : 調整 已用完門檻值
backend -> service.lic
service.lic -> db : 保存設定到租戶底下
return Ok
return
return 成功
==remove brand(TBD)==
autonumber
role -> backend : 停用brand
backend -> service.lic : 停止計費
service.lic -> db : 標註該租戶已停用
return Ok
return Ok
return 成功
==operation history(TBD)==
autonumber
@enduml