# 2.6.x is fail to compile godaddy plugin
FROM caddy:2.5.2-builder AS builder
RUN caddy-builder \
    github.com/caddy-dns/godaddy
#---------------------------------------
FROM caddy:2.5.2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
