apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: backend
  name: license
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: https://dev.license.com
