apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  namespace: backend
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: host.docker.internal:6379
    - name: redisPassword
      secretKeyRef:
        name: "secretstore"
        key: "redis:password"
